---
version: 0.2
phases:
  install:
    runtime-versions:
      docker: 20
      python: 3.9
  build:
    commands:
      - >
        echo '{"registry-mirrors": ["https://mirror.gcr.io"]}' > /etc/docker/daemon.json
      - pkill -1 dockerd
      - make deploy
