#!/usr/bin/env python
import sys
import boto3
from base64 import b64encode

response = boto3.client('kms').encrypt(KeyId='alias/cmk/cfn-secrets', Plaintext=' '.join(sys.argv).encode('utf8'))
print(b64encode(response['CiphertextBlob']))
