#!/usr/bin/env python
import sys
import boto3
from base64 import b64encode
import argparse

if len(sys.argv) > 1:
	plain_text = ' '.join(sys.argv[1:]).encode('utf8')
else:
	plain_text = sys.stdin.buffer.read()

response = boto3.client('kms').encrypt(KeyId='alias/cmk/cfn-secrets', Plaintext=plain_text)
print(b64encode(response['CiphertextBlob']).decode('ascii'))
